### ISSUE TITLE
OpenSSL::SSL::SSLErrorWaitReadable: read would block

### ISSUE THREAD

**Issue by pacoguzman** [Vonage/vonage-ruby-sdk#119]
After updating from 5.0.0 to 5.5.0 on a ruby 2.2.4 application those exceptions started to appear

Any idea of what could be the problem? Thanks in advance

**Comment by timcraft** [comment]
No idea. Do you have a minimal script or test that reproduces the problem? What nexmo-ruby code are you calling when those exceptions appear? Couple of things you could try to narrow it down:

* testing intermediate minor releases of nexmo-ruby
* updating to Ruby 2.2.10

Regardless of where the problem lies I would recommend updating your application's Ruby version if you can, Ruby 2.2.x is unmaintained (and Ruby 2.3.x will be EOL soon too).

**Comment by pacoguzman** [comment]
Yes, we're trying to bump ruby version, but things are slowly, we're in the process to have the gems as up to date as we can, that's why we tried to update `nexmo` as still it's tests are run against ruby 2.2.

We're sending `SMS` with the library from a background process, that uses `sucker-punch`. Could be a multi-thread issue? we're re-using the same client instance in every thread.

We'll try to reproduce the problem with a minimum script in the meantime, thanks for your time.

**Comment by timcraft** [comment]
@pacoguzman Yep, I appreciate the upgrade process can be slow and painful.

Sounds like a threading issue, that would have been my guess. If you change your code to create a new client object inside each background job that should fix any threading problems. You could also use thread-local clients, but creating a client object inside each job is the simplest approach.

**Comment by pacoguzman** [comment]
Thanks, we're going to test that direction, we'll keep you posted. Thanks

**Comment by pacoguzman** [comment]
I'm closing this as creating one client instance each time solved the issue

Thanks for the help.
