### ISSUE TITLE
Buy, cancel, update numbers

### ISSUE THREAD

**Issue by Ank13** [Vonage/vonage-ruby-sdk#17]
Hi Tim,

I didn't see a way to buy, cancel, or update phone numbers in the gem. I think something like this would do it: 
https://github.com/Ank13/nexmo/commit/0cada9ca395ac89efae2c431c1062354126527f4

I'm new to using Nexmo though (and new to pull requests on open source projects), so I wanted to check with you if that makes sense.

Thanks,
Avi

**Comment by timcraft** [comment]
@Ank13 Hi Avi. Makes sense, and commit looks fine. There was a reason I didn't add those methods; struggling to remember exactly why but IIRC they only used to use HTTP GET instead of HTTP POST. Please can you send it as a pull request as that makes it easier to review/merge. If you switch to the branch you should see a button (more info at https://help.github.com/articles/using-pull-requests).

**Comment by Ank13** [comment]
Thanks Tim. I've entered the pull request.
