### ISSUE TITLE
After update, send_message method doesn't return json format

### ISSUE THREAD

**Issue by UlricToinon** [Vonage/vonage-ruby-sdk#27]
Hi,

I did the update of my gem from 1.3.0 to 2.0.0 and i have an error. When I call the "send_message" method, the SMS is sent but  the response format is not json. The return value I get is a string. Is it normal ?

**Comment by timcraft** [comment]
@UlricToinon Yes, that's by design / expected. Version 2.0.0 includes various backwards incompatible changes (hence the major version bump). The behaviour of the #send_message method is now closer to what the #send_message! method was before, i.e. if the message was sent successfully the return value is the message id, and if there was an error an exception will be raised.
