### ISSUE TITLE
error: Message rejected by upstream path

### ISSUE THREAD

**Issue by mustmodify** [Vonage/vonage-ruby-sdk#3]
Following your example, I was not able to send a message.

https://gist.github.com/1653208

**Comment by timcraft** [comment]
I can't see anything wrong with how you're calling it, the same code works for me on ruby 1.9.3p0 if I replace the key/secret/number.

I've just released v0.2.2 which includes the status code in the error message, that might help pinpoint the problem (full list of errors here: http://nexmo.com/documentation/index.html#response_code).

**Comment by JohnGoodman** [comment]
Hey, 

I had the same issue so I did some digging. The issue is caused because the to number is not in international format. If you are in the US ( like me ) just add "1" to the front of your number. Ok, so that fixes that problem. But, it progresses to another problem: Illegal Sender Address - rejected ( status 15 ). If you are in the US and Canada, Nexmo makes you use a virtual number for the send address. Even though the documentation says you can use a string, this faq says otherwise: http://nexmo.zendesk.com/entries/20427093-what-to-specify-in-the-from-field-in-us-and-canada. You can buy a virtual number at: http://dashboard.nexmo.com/private/numbers. 

This is as far as I have gotten so far. I will make another comment when I have more info.

Thanks.

**Comment by timcraft** [comment]
Closing this, please open a new issue if the example code does not work with correctly formatted numbers.

**Comment by sottenad** [comment]
I just ran through this example, and the "from" value needed to be the virtual number that Nexmo assigned to me (including country code), not a name or other string.

**Comment by timcraft** [comment]
@sottenad Yes, country specific restrictions may apply. US messages must originate from either a
pre-approved long number or short code. I've added a note about this to the README.
