### ISSUE TITLE
Support specifying private keys as file paths

### ISSUE THREAD

**Issue by timcraft** [Vonage/vonage-ruby-sdk#59]
Quoting the [spec](https://github.com/Nexmo/client-library-specification/blob/master/SPECIFICATION.md#authenticating-requests):

    MUST allow all credential types as string values,
    may also support alternative values (path to file, etc)

In Ruby reading from a file is a single method call so currently looks like this:

```ruby
client = Nexmo::Client.new({
  application_id: application_id,
  private_key: File.read('path/to/private_key.txt')
})
```

Accepting paths doesn't add much, but would be consistent with other libraries.

**Comment by timcraft** [comment]
@ChrisGuzman @tommorris Thoughts on whether this is necessary?

Reading a file is straightforward in Ruby. If consistency between libraries trumps that then it would help for the spec to specify the heuristic for distinguishing between strings that are pathnames and strings that are key data. Other libraries implement the logic differently (string prefix in nexmo-node, regex in nexmo-java, substring search in nexmo-python).

~If not necessary then can just downgrade the spec requirement from MUST to MAY.~

**Comment by leggetter** [comment]
Good question.

On some platforms (e.g. Heroku) you would not want to deploy the private key file as it likely means committing your private key to source control. Instead of doing this you tend to push the key as a string to an environmental variable.

On these platforms there may be ways to work around this but, for me, it's a big enough consideration to justify making the ability pass the private key value as a string a MUST.

I agree that it'd be a good idea to update the spec to clarify how a key as a string should be identified.

**Comment by timcraft** [comment]
@leggetter Keys can already be passed as a string. So you could use the environment variable approach on Heroku like this:

```ruby
client = Nexmo::Client.new({
  application_id: application_id,
  private_key: ENV['NEXMO_PRIVATE_KEY']
})
```

The issue / question is whether to also support interpreting strings as file paths, which as you say is unlikely in production because you wouldn't want to commit a key to source control.

Just re-reading the spec and I was misreading: path to file is a MAY, whereas string values is a MUST. So I think best just to close this, for development/test it's easy enough to use `File.read`

**Comment by leggetter** [comment]
@timcraft Thanks for clarifying.

I agree that we could just close this :+1:

It was nice conversing 😄

**Comment by mheap** [comment]
> The issue / question is whether to also support interpreting strings as file paths, which as you say is unlikely in production because you wouldn't want to commit a key to source control.

I'm :+1: for closing, as `File.read` is an easy solution (so long as it's documented well). However, we can't assume that people will always use environment variables.

What about projects that call third party executables as children, and don't want the environment to contain sensitive information? They're likely to write the private key to disk using configuration management rather than using environment variables or committing the key to the repo.

**Comment by leggetter** [comment]
> What about projects that call third party executables as children, and
don't want the environment to contain sensitive information? They're likely
to write the private key to disk using configuration management rather than
using environment variables or committing the key to the repo.

In that scenario they do a `File.read` and pass the value to the library as
a String.

This question was to determine if the contents of the String should be
checked to see if was the full key value, a file path or if both should be
supported. We've decided that this library can just support the full key
value option so it's up to the developer to get that value in to a
variable; environment variable and `File.read` are both options there.

**Comment by timcraft** [comment]
Yep, so it's the caller's responsibility to store the `application_id` and `private_key` values somewhere securely, depending on what works best for the application. Plenty of options, but none that really would work well as a default for most use cases.
